### ISSUE TITLE
[Feature] Various driver support e.g. PHP, YAML and XML

### ISSUE THREAD

**Issue by sandrokeil** [mikemix/mxdiModule#1]
Is it possible to support drivers like [Doctrine 2](http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/reference/yaml-mapping.html "Doctrine 2 Metadata Driver") has e.g. PHP, YAML and XML? What do you think?

**Comment by mikemix** [comment]
Would use https://github.com/schmittjoh/metadata to do that. I will definitely think about such feature.

**Comment by mikemix** [comment]
3.0-dev branch on the way :smile:

**Comment by mikemix** [comment]
dev-master has already a working draft of the 3.0 version. Yaml support is now possible, I will start working on XML version in couple of days.

**Comment by sandrokeil** [comment]
This is awesome! :+1:

**Comment by mikemix** [comment]
XML support added :)
